[project]
name = "public-benchmarks-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.82.1",
    "ruff>=0.11.11",
    "runloop-api-client>=0.32.0",
]
